{% set version = "0.4.11" %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: fairscale
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/fairscale/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cdc2327ea1c1c19cf191c621de595e0090602bf43655627bf3d2a7fedb542639
  patches:
    # backport facebookresearch/fairscale#1078 to be able to run test suite
    - patches/0001-chore-move-fair_dev-into-fairscale-1078.patch
    # backport facebookresearch/fairscale#1097 to be able to run test suite
    - patches/0002-add-fair_dev-packages-1097.patch

build:
  number: 0
  # no pytorch on windows in conda-forge, see
  # https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32
  skip: true  # [win]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - sysroot_linux-64 2.17                  # [linux]
    # compilers only needed for CUDA extensions
    - {{ compiler('cxx') }}                  # [cuda_compiler_version != "None"]
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
  host:
    - python
    - pip
    - pytorch
    - pytorch =*={{ torch_proc_type }}*      # [cuda_compiler_version != "None"]
  run:
    - python
    - pgzip
    - pygit2
    - __cuda  # [cuda_compiler_version != "None"]
  run_constrained:
    # additional run constraint to the one from the (version-only) run_export;
    # constraining the CPU builds to CPU pytorch isn't 100% necessary, but cleaner
    - pytorch =*={{ torch_proc_type }}*

test:
  requires:
    - pytest
    - parameterized
    - scikit-learn
    - torchvision
  source_files:
    - tests
  commands:
    # TODO: re-enable tests for unix
    - pytest tests  # [linux]
  imports:
    - fairscale
    - fairscale.nn
    - fairscale.nn.data_parallel
    - fairscale.nn.model_parallel
    - fairscale.nn.pipe
    - fairscale.nn.pipe.balance
    - fairscale.nn.pipe.skip
    - fairscale.optim

about:
  home: https://github.com/facebookresearch/fairscale
  license: BSD-3-Clause
  license_file: LICENSE
  summary: PyTorch extensions for high performance and large scale training.
  dev_url: https://github.com/facebookresearch/fairscale
  doc_url: https://fairscale.readthedocs.io/

extra:
  recipe-maintainers:
    - h-vetinari
